# npm aliases
alias npb='npm build'
alias npc='npm cache'
alias npd='npm dev'
alias npg='npm global'
alias npi='npm install'
alias npl='npm list'
alias npp='npm publish'
alias npr='npm run'
alias nprw='npm run watch'
alias nps='npm start'
alias npsv='npm serve'
alias npt='npm test'
alias npu='npm update'
alias npx='npm exec'
alias npy='npm why'
alias nr='npm run'
