const fs = require('fs');
const path = require('path');
const { minimatch } = require('minimatch')

const listOfIcons = [
  'icon-clap',
  'icon-hands',
  'icon-applause',
  'icon-confetti',
  'icon-announcement',
  'icon-quiz',
  'icon-poll',
  'icon-priority-messages',
  'icon-communities',
  'icon-administration',
  'icon-dashboard-reports',
  'icon-dashboard-admin',
  'icon-insights1',
  'icon-insights',
  'icon-max',
  'icon-sparkle',
  'icon-menu',
  'icon-snooze',
  'icon-campaign_communications',
  'icon-complete-communications',
  'icon-campaigns-tasks',
  'icon-correct-answer',
  'icon-incorrect-answer',
  'icon-embed',
  'icon-edit-data',
  'icon-viewers',
  'icon-reach',
  'icon-training',
  'icon-training-catalog',
  'icon-learnerzone',
  'icon-home',
  'icon-admin_home',
  'icon-guided_learning',
  'icon-path',
  'icon-training-plan',
  'icon-task',
  'icon-todo',
  'icon-intro',
  'icon-light_bulb',
  'icon-bulb',
  'icon-discoveryzone',
  'icon-achievements',
  'icon-games',
  'icon-gamepad',
  'icon-GameChallengeLoss',
  'icon-GameChallengeWon',
  'icon-fire',
  'icon-uniF2DC',
  'icon-rewards',
  'icon-events',
  'icon-tellafriend',
  'icon-profile',
  'icon-user',
  'icon-uniF2C0',
  'icon-uniF2BE',
  'icon-uniF2BD',
  'icon-logout',
  'icon-leaderzone',
  'icon-usermetrics',
  'icon-teammetrics',
  'icon-impacts',
  'icon-compare',
  'icon-teammessage',
  'icon-random',
  'icon-groups',
  'icon-group',
  'icon-admin_zone',
  'icon-content',
  'icon-pencil',
  'icon-programs',
  'icon-reports',
  'icon-compass',
  'icon-support',
  'icon-_433',
  'icon-cog',
  'icon-settings',
  'icon-bolt',
  'icon-bolt1',
  'icon-very_sure',
  'icon-somewhat_sure',
  'icon-filter',
  'icon-public-filters',
  'icon-advanced-filter',
  'icon-pop',
  'icon-calendar',
  'icon-calendar-outline',
  'icon-calendar_empty',
  'icon-calendar-check',
  'icon-calendar-pending',
  'icon-frequenttraining',
  'icon-ParticipationFrequency10',
  'icon-ParticipationFrequency15',
  'icon-ParticipationFrequency20',
  'icon-ParticipationFrequency25',
  'icon-ParticipationFrequency30',
  'icon-GameHighScore1',
  'icon-GameHighScore2',
  'icon-GameHighScore3',
  'icon-CorrectAnswerStreak1',
  'icon-CorrectAnswerStreak10',
  'icon-CorrectAnswerStreak20',
  'icon-CorrectAnswerStreak50',
  'icon-CorrectAnswerStreak100',
  'icon-CorrectAnswerStreak200',
  'icon-CorrectAnswerStreak500',
  'icon-CorrectAnswerStreak1000',
  'icon-_388',
  'icon-graduated',
  'icon-TopicLevelGraduation1',
  'icon-TopicLevelGraduationStreak1',
  'icon-TopicLevelGraduationStreak2',
  'icon-TopicLevelGraduationStreak3',
  'icon-TopicLevelGraduationStreak5',
  'icon-TopicLevelGraduationStreak10',
  'icon-TopicLevelGraduationStreak15',
  'icon-TopicLevelGraduationStreak20',
  'icon-TopicLevelGraduationStreak30',
  'icon-TopicLevelGraduationStreak50',
  'icon-TopicLevelGraduationStreak75',
  'icon-TopicLevelGraduationStreak100',
  'icon-TopicLevelGraduationStreak150',
  'icon-SessionStreak1',
  'icon-SessionStreak10',
  'icon-SessionStreak20',
  'icon-SessionStreak50',
  'icon-SessionStreak100',
  'icon-SessionStreak200',
  'icon-SessionStreak500',
  'icon-SessionStreak1000',
  'icon-unlink-item',
  'icon-indent-link',
  'icon-link-item',
  'icon-unindent-link',
  'icon-sliders',
  'icon-_449',
  'icon-not-started',
  'icon-beginner',
  'icon-adjust',
  'icon-intermediate',
  'icon-training_activity',
  'icon-star-outline',
  'icon-star-solid',
  'icon-thumbtack-outline',
  'icon-thumbtack',
  'icon-pushpin',
  'icon-pending',
  'icon-time',
  'icon-create-article-nobg',
  'icon-create-article',
  'icon-external_link',
  'icon-create-link-nobg',
  'icon-create-link',
  'icon-create-dz',
  'icon-broadcast',
  'icon-bullhorn',
  'icon-hub_activity',
  'icon-question_summary',
  'icon-contentexchange',
  'icon-content-marketplace',
  'icon-squiggle',
  'icon-needsreview',
  'icon-survey',
  'icon-check',
  'icon-ok',
  'icon-ok_circle',
  'icon-ok_sign',
  'icon-checkbox-outline',
  'icon-underconfident',
  'icon-correct_observation',
  'icon-due_certs',
  'icon-warning_sign',
  'icon-needs_coaching',
  'icon-incorrect_observation',
  'icon-exclamation',
  'icon-exclamation_sign-outline',
  'icon-exclamation_sign',
  'icon-dashboard',
  'icon-reportcard',
  'icon-knowledge',
  'icon-metrics',
  'icon-_479',
  'icon-bar_chart',
  'icon-_480',
  'icon-chart-area',
  'icon-chart-line',
  'icon-_529',
  'icon-_530',
  'icon-non_participants',
  'icon-user_switch',
  'icon-overdue_certs',
  'icon-certifications',
  'icon-extratraining',
  'icon-news',
  'icon-_460',
  'icon-timeline',
  'icon-refresher',
  'icon-coffee',
  'icon-trophy',
  'icon-topperformers',
  'icon-trophy-gold',
  'icon-trophy-silver',
  'icon-trophy-bronze',
  'icon-team-trophy-gold',
  'icon-team-trophy-silver',
  'icon-team-trophy-bronze',
  'icon-inspections',
  'icon-zoom_in',
  'icon-zoom_out',
  'icon-search',
  'icon-ban_circle',
  'icon-envelope_alt',
  'icon-envelope',
  'icon-heart_empty',
  'icon-heart',
  'icon-pause',
  'icon-play',
  'icon-play_sign',
  'icon-onboarding_topic',
  'icon-microphone',
  'icon-microphone_off',
  'icon-film',
  'icon-video',
  'icon-camera',
  'icon-camera_retro',
  'icon-camera-plus',
  'icon-picture',
  'icon-image',
  'icon-file_alt',
  'icon-_550',
  'icon-sitemap',
  'icon-th_large',
  'icon-th_list',
  'icon-lock-forgot-password',
  'icon-lock',
  'icon-unlock_alt',
  'icon-unlock',
  'icon-key',
  'icon-tag',
  'icon-print',
  'icon-map_marker',
  'icon-add-above',
  'icon-add-below',
  'icon-plus',
  'icon-plus_sign',
  'icon-plus_square_o',
  'icon-f0fe',
  'icon-minus',
  'icon-check_minus',
  'icon-minus_sign_alt',
  'icon-medium',
  'icon-minus_sign',
  'icon-remove',
  'icon-remove_sign',
  'icon-remove_circle',
  'icon-overconfident',
  'icon-question',
  'icon-create-question-nobg',
  'icon-question_sign',
  'icon-create-question',
  'icon-info_sign',
  'icon-_279',
  'icon-screenshot',
  'icon-asterisk',
  'icon-behaviors',
  'icon-eye_open',
  'icon-eye_close',
  'icon-uniF2A8',
  'icon-legal',
  'icon-ticket',
  'icon-slots',
  'icon-shopping_cart',
  'icon-thumbs_down_alt',
  'icon-_334',
  'icon-thumbs_up_alt',
  'icon-upload',
  'icon-upload_alt',
  'icon-download',
  'icon-download_alt',
  'icon-downloads',
  'icon-bookmark_empty',
  'icon-bookmark',
  'icon-paper_clip',
  'icon-link',
  'icon-unlink',
  'icon-copy',
  'icon-_553',
  'icon-high',
  'icon-low',
  'icon-arrow_down',
  'icon-arrow_left',
  'icon-arrow_right',
  'icon-caret_down',
  'icon-caret_up',
  'icon-caret_left',
  'icon-caret_right',
  'icon-angle_up',
  'icon-angle_down',
  'icon-angle_left',
  'icon-angle_right',
  'icon-chevron_up',
  'icon-chevron_down',
  'icon-chevron_left',
  'icon-chevron_right',
  'icon-double_angle_up',
  'icon-double_angle_down',
  'icon-double_angle_left',
  'icon-double_angle_right',
  'icon-move',
  'icon-fullscreen',
  'icon-resize_full',
  'icon-resize_small',
  'icon-resize_vertical',
  'icon-resize_horizontal',
  'icon-exchange',
  'icon-undo',
  'icon-reply',
  'icon-refresh',
  'icon-reinforcement',
  'icon-share_alt',
  'icon-retweet',
  'icon-comment',
  'icon-comment_alt',
  'icon-comments',
  'icon-comments_alt',
  'icon-notification',
  'icon-bell_alt',
  'icon-bell',
  'icon-file_text',
  'icon-file_text_alt',
  'icon-game_popularity',
  'icon-desktop',
  'icon-keyboard',
  'icon-mobile_phone',
  'icon-phone',
  'icon-circle_blank',
  'icon-_446',
  'icon-circle',
  'icon-dot_circle_alt',
  'icon-bullseye',
  'icon-archive',
  'icon-category',
  'icon-folder_close',
  'icon-folder_close_alt',
  'icon-folder_open',
  'icon-folder_open_alt',
  'icon-milestone',
  'icon-reported',
  'icon-flag',
  'icon-flag_alt',
  'icon-flag_checkered',
  'icon-ellipsis_horizontal',
  'icon-ellipsis_vertical',
  'icon-trash',
  'icon-_473',
  'icon-_484',
  'icon-_485',
  'icon-shield',
  'icon-sort_by_alphabet',
  'icon-_329',
  'icon-sort_by_attributes',
  'icon-sort_by_attributes_alt',
  'icon-sort_by_order',
  'icon-sort_by_order_alt',
  'icon-font',
  'icon-bold',
  'icon-italic',
  'icon-underline',
  'icon-strikethrough',
  'icon-header',
  'icon-text_height',
  'icon-text_width',
  'icon-list',
  'icon-ul',
  'icon-ol',
  'icon-exam',
  'icon-reorder',
  'icon-table',
  'icon-pdf',
  'icon-spreadsheet',
  'icon-slide',
  'icon-doc',
  'icon-file',
  'icon-zip',
  'icon-audio',
  'icon-message-plus',
  'icon-suggestquestion',
  'icon-cogs',
  'icon-_557',
  'icon-_558',
  'icon-switch_on',
  'icon-switch_off',
  'icon-facebook',
  'icon-facebook-logo',
  'icon-facebook_sign',
  'icon-linkedin',
  'icon-linkedin_sign',
  'icon-google_plus',
  'icon-googleplus-logo',
  'icon-salesforce-logo',
  'icon-zendesk-logo',
  'icon-mostactive',
  'icon-stats',
  'icon-uniF1C0',
  'icon-th',
  'icon-male',
  'icon-integration',
  'icon-publish',
  'icon-evaluations',
  'icon-source-info',
  'icon-translate',
  'icon-send',
  'icon-like-path1',
  'icon-like-path2',
  'icon-love-path1',
  'icon-love-path2',
  'icon-celebrate-path1',
  'icon-celebrate-path2',
  'icon-thinking-path1',
  'icon-thinking-path2',
  'icon-upset-path1',
  'icon-upset-path2'
];

const targetDirectory = '/Users/bernardobechtold/projects/thunderball/axonify-client-web'; // Specify your codebase path here
const variableNames = listOfIcons; // List of variable names to check
const excludeFiles = ['excludedFile1.js', 'excludedFile2.js']; // List of files to exclude
const allowedExtensions = ['.js', '.ts', '.tsx', '.jsx', '.css', '.less']; // List of allowed extensions
const excludePatterns = ['**/public/**', '**/vendor/**', '**/target/**']; // List of patterns to exclude

// Recursively read all files in the directory
const getFiles = (dir, files) => {
  files = files || [];
  const items = fs.readdirSync(dir);
  for (const item of items) {
    const fullPath = path.join(dir, item);
    if (fs.statSync(fullPath).isDirectory()) {
      getFiles(fullPath, files);
    } else if (
      allowedExtensions.includes(path.extname(fullPath)) && 
      !excludeFiles.includes(path.basename(fullPath)) &&
      !excludePatterns.some(pattern => minimatch(fullPath, pattern))
    ) {
      files.push(fullPath);
    }
  }
  return files;
};

// Check if a file contains any of the variables
const checkFileForVariables = (file, variables) => {
  const content = fs.readFileSync(file, 'utf-8');
  return variables.filter(variable => content.includes(variable));
};

// Convert JSON to CSV format
const jsonToCsv = (json) => {
  const headers = 'Variable,Used\n';
  const rows = Object.keys(json)
    .map(key => `${key},${json[key]}`)
    .join('\n');
  return headers + rows;
};

// Main function to search for the variables
const findVariablesUsage = (dir, variables) => {
  const files = getFiles(dir);
  const variablesUsage = variables.reduce((acc, variable) => {
    acc[variable] = false;
    return acc;
  }, {});

  files.forEach(file => {
    const foundVariables = checkFileForVariables(file, variables);
    foundVariables.forEach(variable => {
      variablesUsage[variable] = true;
    });
  });

  // Save the results to a JSON file
  fs.writeFileSync('variablesUsage.json', JSON.stringify(variablesUsage, null, 2));
  fs.writeFileSync('variablesUsage.csv', jsonToCsv(variablesUsage));
  
  console.log('The variable usage information has been saved to variablesUsage.json');
};

// Run the script
findVariablesUsage(targetDirectory, variableNames);
